name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: Build (${{ matrix.OS }})
    strategy:
      fail-fast: false
      matrix:
        OS: ["macos-12", "ubuntu-latest"]
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v3

      - uses: coursier/cache-action@v6

      - uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: temurin:17
          power: true

      - run: sudo apt install -y xinerama xcursor xorg libglu1-mesa pkg-config          
        if: startsWith(matrix.os, 'ubuntu-') 

      - name: CI and build the binary
        run: ./build.sc app-platform-release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: little-fingers-*
          name: ${{ matrix.os }}-binaries
          if-no-files-found: error
