name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: Build (${{ matrix.OS }})
    strategy:
      fail-fast: true
      matrix:
        OS: ["macos-12", "macos-14", "ubuntu-latest"]
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: adopt:17

      - name: CI and build the binary
        run: ./build.sc app-platform-release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: little-fingers-*
          name: ${{ matrix.os }}-binaries
          if-no-files-found: error
